### ISSUE TITLE
Compatibility with latest Keystone version

### ISSUE THREAD

**Issue by mickaelchanrion** [keystonejs/keystone-storage-adapter-s3#31]
Is this adapter compatible with the last version of keystone (beta) ?

**Comment by cvn** [comment]
Yes, it is. I've been using it with keystone 4.0.0-beta.8.

**Comment by mickaelchanrion** [comment]
Not working with the region 'eu-central-1' (due to knox which is not supporting the auth' mechanism, see this [issue](https://github.com/Automattic/knox/issues/254))
So I used a fork of stevenkaspr. He implemented aws-sdk instead of knox. 
For anyone interested, the repo is [here](https://github.com/stevenkaspar/keystone-storage-adapter-s3)

**Comment by mikehazell** [comment]
v2.0.0 has been released today which resolves this issue.

This is a major version bump because the api around setting custom params on the uploaded objects has changed.

If you were using `headers` previously you will need to modify your code to use `uploadParams`. Check the read me for examples.
