### ISSUE TITLE
ACL: "public-read"

### ISSUE THREAD

**Issue by g3r4n** [keystonejs/keystone-storage-adapter-s3#36]
ACL in uploadParams don't seems to work.
I've tried with keystone-storage-adapter-s3 v2.0.0

**Comment by g3r4n** [comment]
got only the issue for file with a spaces in the name.

**Comment by mikehazell** [comment]
@g3r4n - This is working for me. Can you post your adapter config?

**Comment by g3r4n** [comment]
@mikehazell Yes i can confirm the issue comes from files with spaces in the name. i used the generateFilename option to fixe it.
By the way, this option is not documented.

**Comment by mikehazell** [comment]
Ok thanks @g3r4n. Were you seeing this issue with the default `generateFileName` option (ie. random filename) or were you using something custom?

**Comment by g3r4n** [comment]
@mikehazell It was with a custom generateFileName function. Maybe we can improve the code by flaging something in the console ?
Thanks for your work and your quick replies :)

**Comment by mikehazell** [comment]
Yeah, a console warning might be helpful. Would be interesting to know if other characters cause this issue. Thanks for the heads up.

**Comment by jennaprice** [comment]
I am having this issue as well. I am getting with devops to see if its a permissions error, but I cannot upload images if I use the upload params

**Comment by g3r4n** [comment]
@jennaprice did you try to upload a file without space in the name ?

**Comment by jennaprice** [comment]
@g3r4n Hmm I just saw this, it turned out to be a permission issue from DevOps after a ton of troubleshooting.
