### ISSUE TITLE
Original Filename

### ISSUE THREAD

**Issue by jstockwin** [keystonejs/keystone-storage-adapter-s3#7]
Previously with `Types.S3File` the database also stored `originalname`, however this doesn't seem to be possible anymore. It would be nice to be able to continue doing this. 

It's documented with the keystone File field type [here](https://github.com/keystonejs/keystone/tree/master/fields/types/file#file-field), but there it says that the adapter can override these fields, so I assume it's this breaking it? If not, happy to close this and re-open against keystone itself.

**Comment by JedWatson** [comment]
@jstockwin not sure why that's not working, if you've got the schema set up to store the original filename it should do so, if there's a bug in there I don't think it is adapter specific but would need to do more testing to confirm.

**Comment by jstockwin** [comment]
@JedWatson I think maybe I'm missing something. Previously I didn't need to add anything to the schema, the `originalname` was just stored automatically... Do I now need to add an option to make this happen?

**Comment by JedWatson** [comment]
@jstockwin see the [storage docs](https://github.com/keystonejs/keystone/tree/master/lib/storage#schema), I've just added a clarification on which schema paths are enabled by default. The change from `originalname` always being stored is something we need to note in the update guide when explaining how to update from `LocalFile` / `S3File` fields.

**Comment by jstockwin** [comment]
Alright, thanks for the clarification.
